### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Nefertumm** [Nefertumm/InventorySystem#1]
- [ ] Add usage to items, make that virtual maybe.
- [ ] Implement DB usage for players and inventory, why not lmao.
- [ ] Send items system?
- [ ] For god sake, split in .h and .cpp
- [ ] I don't really like how the addItem and removeItem is implemented, so... perhaps rewrite it soon?
- [ ] Related to split, but purge the test scenario.
- [ ] So far, I only have bag management... Implement equipment slots (rogue/rpg like). Should I add it into the inventory? Who knows lmao
